package com.businessLibellum

interface IConstantes {
    String USUARIO_LOGUEADO = "USUARIO_LOGUEADO"
    String EMPRESA_SELECCIONADA = "EMPRESA_SELECCIONADA"

    //METODOS DE PAGO
    String EFECTIVO = "EFECTIVO"
    String CREDITO = "CRÉDITO"
    String TARJETA_CREDITO = "TARJETA DE CREDITO"

    //COMPROBANTES
    String CONSUMIDOR_FINAL = "CONSUMIDOR FINAL"
    String CREDITO_FISCAL = "CRÉDITO FISCAL"
    String ESPECIAL = "ESPECIAL"
    String GUBERNAMENTAL = "GUBERNAMENTAL"

    //COMPROBANTES
    String FACTURA_NORMAL = "FACTURA"
    String FACTURA_CREDITO_FISCAL = "FACTURA CRÉDITO FISCAL"

}